# Generated by Django 2.1.3 on 2018-12-13 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20181212_1503'),
        ('members', '0004_user_site_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='likeitem',
            unique_together={('user', 'item')},
        ),
    ]
