# Generated by Django 2.1.3 on 2018-12-14 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20181213_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
