# Generated by Django 2.1.3 on 2018-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=50)),
                ('origin_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('discount_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
