# Generated by Django 2.1.3 on 2018-11-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='photo_type',
            field=models.CharField(choices=[('T', 'thumbnail'), ('D', 'detail'), ('L', 'list_thumbnail')], max_length=1),
        ),
    ]
