# Generated by Django 2.1.3 on 2018-11-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='regular_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
