# Generated by Django 2.1.3 on 2018-11-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_description_regular_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='dom',
            field=models.CharField(max_length=100),
        ),
    ]
