# Generated by Django 2.1.3 on 2018-11-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20181127_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_order',
            field=models.IntegerField(default=1),
        ),
    ]
