# Generated by Django 2.1.3 on 2018-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20181127_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='', upload_to='Category'),
            preserve_default=False,
        ),
    ]
