# Generated by Django 2.1.3 on 2018-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
