# Generated by Django 2.1.3 on 2018-11-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20181127_2107'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
