# Generated by Django 2.1.3 on 2018-11-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20181128_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list_thumbnail',
            field=models.ImageField(default='', upload_to='Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='photo_type',
            field=models.CharField(choices=[('T', 'thumbnail'), ('D', 'detail')], max_length=1),
        ),
    ]
