# Generated by Django 2.1.3 on 2018-11-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20181129_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ga_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
