# Generated by Django 2.1.3 on 2018-12-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20181130_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['-photo_type', 'image_order']},
        ),
    ]
