# Generated by Django 2.1.3 on 2018-12-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='익명 사용자', max_length=50),
        ),
    ]
