# Generated by Django 2.1.3 on 2018-12-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20181210_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='item_type',
            field=models.CharField(max_length=100),
        ),
    ]
