# Generated by Django 2.1.3 on 2018-12-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_comment_nickname'),
        ('items', '0019_auto_20181210_1723'),
    ]

    operations = [
    ]
