# Generated by Django 2.1.3 on 2018-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_merge_20181212_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='capacity',
            field=models.CharField(max_length=300),
        ),
    ]
