# Generated by Django 2.1.3 on 2018-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20181129_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['order_date_time']},
        ),
        migrations.AddField(
            model_name='basket',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
