# Generated by Django 2.1.3 on 2018-12-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20181130_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='sale_price',
        ),
    ]
