# Generated by Django 2.1.3 on 2018-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_remove_basket_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
